### PR TITLE
programmatic left/right swipe

### PR DESCRIPTION
**Pull request by abrarmusa**
Adds two functions which can be called:

_forceLeftSwipe()
_forceRightSwipe()

Also has @clintonjrobinson 's stack feature

### CODE REVIEW

**Comment by jjoe64** [comment]
please merge it

**Comment by vitorebatista** [comment]
This branch has conflicts that must be resolved...

**Comment by jjoe64** [comment]
maybe i will merge it the next days...

**Comment by jjoe64** [comment]
can be closed see #47

**Pull request closed without merging**
