### PR TITLE
Adding stack feature

### PR DESCRIPTION
**Pull request by clintonjrobinson**
Adding the ability to show the cards as a stack using stack={true}

### CODE REVIEW

**Comment by divyekhanna** [comment]
Hey, does this PR enable displaying the next card as the top card (in the deck) is being swiped?

**Comment by yogiben** [comment]
@clintonjrobinson could you elaborate a little?

Sorry for the slow reply. I'm just merging now.

**Comment by divyekhanna** [comment]
@yogiben I tried this feature, and it enables stacking of cards (tinder-like) by setting prop `stack={true}` to the `SwipeCards` component. Other properties that can be set are `stackDepth`, `stackOffsetX` and `stackOffsetY`.

**Comment by tslater** [comment]
Really cool!

**Comment by tslater** [comment]
Is this something that will end up being merged in/is it just being held up by merge conflicts? Or is it not something that will get added?

**Comment by abrarmusa** [comment]
Has this been resolved yet?

**Comment by jsanchezs** [comment]
Please, merge! =)

**Comment by vcalvello** [comment]
+1

**Comment by duataud** [comment]
+1

**Comment by indivisable** [comment]
Will this be merged?

**Comment by giangstrider** [comment]
Does it will be merge? I really need this feature.

**Comment by florianbepunkt** [comment]
+1

**Comment by florianbepunkt** [comment]
I am trying to use this pull request, but it produces issues when it comes to styling. any advice on how to center the stack of cards on a page (both landscape and portrait mode)? absolute positioning of the stack doesn't seem to play nicely with flexbox

**Review by vitorebatista — APPROVED** [review]

**Comment by vitorebatista** [comment]
@clintonjrobinson could you resolve the conflict?

**Comment by jjoe64** [comment]
can be closed see #47

**Pull request closed without merging**
